# Generated by Django 4.0 on 2021-12-08 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='name',
            new_name='title',
        ),
    ]
